// Auto-generated by scripts/export-to-files.ts on 2026-04-21T08:08:23.568Z
// Edit this file directly when adding/updating destinations.
// No DB queries used for public-facing reads.

export type DestinationData = {
  id: string
  name: string
  country: string
  slug: string | null
  category: string
  imageUrl: string | null
  description: string | null
  popularity: number | null
  bestSeason: string | null
  targetAudience: string | null
}

export const destinations: DestinationData[] = [
  {
    "id": "andalusia",
    "name": "Andalusia",
    "country": "Spagna",
    "slug": "andalusia",
    "category": "citta",
    "imageUrl": null,
    "description": "Regione del sud con Siviglia, Granada, Malaga",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "antalya",
    "name": "Antalya",
    "country": "Turchia",
    "slug": "antalya",
    "category": "mare",
    "imageUrl": null,
    "description": "Riviera turca, resort tutto incluso a prezzi top",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "cmo1qt6500000z4nsd5sy7vy7",
    "name": "Aruba",
    "country": "Karibik",
    "slug": "aruba",
    "category": "isola",
    "imageUrl": null,
    "description": "Aruba, die karibische Sonneninsel vor der Küste Venezuelas, verzaubert mit weißen Puderzuckerstränden, türkisblauem Meer, ganzjährig warmem Klima und einer einzigartigen Mischung aus niederländischem Charme und karibischer Lebensfreude.",
    "popularity": null,
    "bestSeason": "November - April",
    "targetAudience": null
  },
  {
    "id": "bad-griesbach",
    "name": "Bad Griesbach",
    "country": "Germania",
    "slug": "bad-griesbach",
    "category": "wellness",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "bali",
    "name": "Bali",
    "country": "Indonesia",
    "slug": "bali",
    "category": "avventura",
    "imageUrl": null,
    "description": "La meta Instagrammabile che vende emozione",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "bodrum",
    "name": "Bodrum",
    "country": "Turchia",
    "slug": "bodrum",
    "category": "mare",
    "imageUrl": null,
    "description": "Costa Egea, vita notturna e boutique hotel",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "cairo",
    "name": "Cairo",
    "country": "Egitto",
    "slug": "cairo",
    "category": "citta",
    "imageUrl": null,
    "description": "Piramidi, storia millenaria",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "calabria",
    "name": "Calabria",
    "country": "Italia",
    "slug": "calabria",
    "category": "mare",
    "imageUrl": null,
    "description": "Costa degli Dei, mare cristallino e prezzi accessibili",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "canarie",
    "name": "Canarie",
    "country": "Spagna",
    "slug": "canarie",
    "category": "mare",
    "imageUrl": null,
    "description": "Arcipelago nell'Atlantico con clima perfetto tutto l'anno",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "chalkidiki",
    "name": "Chalkidiki",
    "country": "Grecia",
    "slug": "chalkidiki",
    "category": "mare",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "corf",
    "name": "Corfù",
    "country": "Grecia",
    "slug": "corf",
    "category": "mare",
    "imageUrl": null,
    "description": "Isola verde dello Ionio",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "creta",
    "name": "Creta",
    "country": "Grecia",
    "slug": "creta",
    "category": "mare",
    "imageUrl": null,
    "description": "Isola più grande della Grecia, storia e spiagge",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "dalaman",
    "name": "Dalaman",
    "country": "Turchia",
    "slug": "dalaman",
    "category": "mare",
    "imageUrl": null,
    "description": "Ölüdeniz, laguna blu e paragliding",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "fuessen",
    "name": "Füssen",
    "country": "Germania",
    "slug": "fuessen",
    "category": "citta",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "holland",
    "name": "Holland",
    "country": "Paesi Bassi",
    "slug": "holland",
    "category": "avventura",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "hurghada",
    "name": "Hurghada",
    "country": "Egitto",
    "slug": "hurghada",
    "category": "mare",
    "imageUrl": null,
    "description": "Mar Rosso, snorkeling e diving spettacolari",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "istanbul",
    "name": "Istanbul",
    "country": "Turchia",
    "slug": "istanbul",
    "category": "citta",
    "imageUrl": null,
    "description": "Metropoli tra Europa e Asia",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "izmir",
    "name": "Izmir",
    "country": "Turchia",
    "slug": "izmir",
    "category": "citta",
    "imageUrl": null,
    "description": "Terza città turca, vicina a Efeso",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "cmo1du2r00000k4ns7ggnd779",
    "name": "Korfu",
    "country": "Griechenland",
    "slug": "korfu",
    "category": "isola",
    "imageUrl": null,
    "description": "Korfu, die smaragdgrüne Insel im Ionischen Meer, verzaubert mit malerischen Buchten, kristallklarem Wasser, venezianischer Architektur und üppiger Vegetation. Ideal für Familien, Paare und Strandurlauber.",
    "popularity": null,
    "bestSeason": "Mai - Oktober",
    "targetAudience": null
  },
  {
    "id": "kos",
    "name": "Kos",
    "country": "Grecia",
    "slug": "kos",
    "category": "mare",
    "imageUrl": null,
    "description": "Piccola isola greca con spiagge infinite",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "lago-di-garda",
    "name": "Lago di Garda",
    "country": "Italia",
    "slug": "lago-di-garda",
    "category": "avventura",
    "imageUrl": null,
    "description": "Il lago più grande d'Italia, sport e relax",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "mallorca",
    "name": "Mallorca",
    "country": "Spagna",
    "slug": "mallorca",
    "category": "mare",
    "imageUrl": null,
    "description": "Isola più grande delle Baleari, perfetta per turisti tedeschi",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "marbella",
    "name": "Marbella",
    "country": "Spagna",
    "slug": "marbella",
    "category": "mare",
    "imageUrl": null,
    "description": "Costa del Sol, lusso e vita notturna",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "mauritius",
    "name": "Mauritius",
    "country": "Mauritius",
    "slug": "mauritius",
    "category": "mare",
    "imageUrl": null,
    "description": "Paradiso tropicale nell'Oceano Indiano",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "mont-saint-michel",
    "name": "Mont-Saint-Michel",
    "country": "Francia",
    "slug": "mont-saint-michel",
    "category": "citta",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "nordkroatien",
    "name": "Nordkroatien",
    "country": "Croazia",
    "slug": "nordkroatien",
    "category": "avventura",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "playa-del-carmen",
    "name": "Playa del Carmen",
    "country": "Messico",
    "slug": "playa-del-carmen",
    "category": "mare",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "punta-cana",
    "name": "Punta Cana",
    "country": "Rep. Dominicana",
    "slug": "punta-cana",
    "category": "mare",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "rodi",
    "name": "Rodi",
    "country": "Grecia",
    "slug": "rodi",
    "category": "mare",
    "imageUrl": null,
    "description": "Isola del sole, Dodecaneso",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "cmnncdgzk000004i8fgi88h2e",
    "name": "Salento",
    "country": "Italien",
    "slug": "salento",
    "category": "mare",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "cmnf0yjb70000eknsfftcmuex",
    "name": "Sansibar",
    "country": "Tansania",
    "slug": "sansibar",
    "category": "isola",
    "imageUrl": null,
    "description": "Tropisches Inselparadies vor der Kueste Ostafrikas mit weissen Sandstraenden und tuerkisblauem Wasser",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "santorini",
    "name": "Santorini",
    "country": "Grecia",
    "slug": "santorini",
    "category": "mare",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "sardegna",
    "name": "Sardegna",
    "country": "Italia",
    "slug": "sardegna",
    "category": "mare",
    "imageUrl": null,
    "description": "Spiagge caraibiche nel Mediterraneo",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "sharm-el-sheikh",
    "name": "Sharm el-Sheikh",
    "country": "Egitto",
    "slug": "sharm-el-sheikh",
    "category": "mare",
    "imageUrl": null,
    "description": "Resort sul Mar Rosso, barriera corallina",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "sicilia",
    "name": "Sicilia",
    "country": "Italia",
    "slug": "sicilia",
    "category": "mare",
    "imageUrl": null,
    "description": "Cultura, cibo e mare straordinari",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "suedtirol",
    "name": "Südtirol",
    "country": "Italia",
    "slug": "suedtirol",
    "category": "montagna",
    "imageUrl": null,
    "description": "Alto Adige — montagne, wellness e cultura bilingue",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "thailandia",
    "name": "Thailandia",
    "country": "Thailandia",
    "slug": "thailandia",
    "category": "avventura",
    "imageUrl": null,
    "description": "La meta long-haul da sogno, spiagge e cultura",
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  },
  {
    "id": "zypern",
    "name": "Zypern",
    "country": "Cipro",
    "slug": "zypern",
    "category": "mare",
    "imageUrl": null,
    "description": null,
    "popularity": null,
    "bestSeason": null,
    "targetAudience": null
  }
]

export function getDestinationBySlug(slug: string): DestinationData | undefined {
  return destinations.find((d) => d.slug === slug)
}

export function getDestinationById(id: string): DestinationData | undefined {
  return destinations.find((d) => d.id === id)
}
